@extends('layout/layout_base')

@php
    /** @var array<string, \App\ValueObject\PhpstanRule[]> $groupedRules */
    /** @var int $totalCount */
    /** @var string|null $generatedAt */
    /** @var array<string, \App\ValueObject\PhpstanRulePackage> $packagesByName */
@endphp

@section('content')
    <div class="container">
        <h1>Discover PHPStan Rules</h1>

        <div class="mt-4 mb-4">
            <p>
                A searchable index of <strong>{{ $totalCount }} individual PHPStan rules</strong>
                from the most popular community packages. Each entry shows the rule's class, what it does,
                and (where the package documents it) a wrong/correct code example.
            </p>
            <p class="text-secondary" style="font-size: .9em;">
                Generated by scanning installed rule classes
                @if ($generatedAt)
                    &middot; last refreshed {{ \Carbon\Carbon::parse($generatedAt)->diffForHumans() }}
                @endif
            </p>
        </div>

        <div class="mb-4">
            <input
                type="search"
                id="rule-search"
                class="form-control form-control-lg shadow-sm"
                placeholder="Search rules by class, message, package... (e.g. forbidCast, ergebnis, mixed)"
                autocomplete="off"
            >
            <div id="search-match-count" class="text-secondary mt-2" style="font-size: .9em; display: none;"></div>
        </div>

        <div class="mb-4" id="package-nav">
            @foreach ($groupedRules as $package => $rules)
                @php $navInfo = $packagesByName[$package] ?? null; @endphp
                <a
                    href="#pkg-{{ str($package)->slug() }}"
                    class="badge text-bg-dark text-decoration-none me-2 mb-2"
                    style="font-size: .9em; padding: .55em .8em;"
                    @if ($navInfo && $navInfo->getDescription()) title="{{ $navInfo->getDescription() }}" @endif
                >
                    {{ $package }}
                    <span class="opacity-75">({{ count($rules) }})</span>
                </a>
            @endforeach
        </div>

        <p class="text-secondary" id="no-results" style="display: none;">
            No rules match your search.
        </p>

        @foreach ($groupedRules as $package => $rules)
            @php $packageInfo = $packagesByName[$package] ?? null; @endphp
            <div class="rule-group" data-package="{{ strtolower($package) }}">
                <a name="pkg-{{ str($package)->slug() }}"></a>
                <h2 class="mt-5 mb-2" style="border-bottom: 2px solid #eee; padding-bottom: .3em; color: #333;">
                    {{ $package }}
                    <small class="text-secondary" style="font-size: .55em; font-weight: normal;">
                        {{ count($rules) }} rule{{ count($rules) > 1 ? 's' : '' }}
                    </small>
                </h2>

                <div class="mb-3" style="font-size: .95em;">
                    @if ($packageInfo && $packageInfo->getDescription())
                        <p class="mb-1 text-secondary">{{ $packageInfo->getDescription() }}</p>
                    @endif
                    <pre class="mb-2" style="background: #f8f9fa; border: 1px solid #e9ecef; border-radius: .3em; padding: .5em .8em; font-size: .85em; margin: 0;"><code>composer require --dev {{ $package }}</code></pre>
                    <div style="font-size: .9em;">
                        @if ($packageInfo && $packageInfo->getUrl())
                            <a href="{{ $packageInfo->getUrl() }}" rel="noopener" target="_blank" class="text-decoration-none">GitHub</a>
                            <span class="text-secondary mx-1">&middot;</span>
                        @endif
                        <a href="https://packagist.org/packages/{{ $package }}" rel="noopener" target="_blank" class="text-decoration-none">Packagist</a>
                    </div>
                </div>

                @foreach ($rules as $rule)
                    @php
                        $haystackParts = array_filter([
                            $rule->getClass(),
                            $rule->getName(),
                            $rule->getMessage(),
                            $rule->getDescription(),
                            $rule->getPackage(),
                            $rule->getGroup(),
                            $rule->getNodeType(),
                            // split camelCase so per-token fuzzy can match "forbid cast" inside "ForbidCastRule"
                            preg_replace('/(?<=[a-z0-9])(?=[A-Z])/', ' ', $rule->getClass() . ' ' . $rule->getName()),
                        ]);
                        $searchHaystack = strtolower(implode(' ', $haystackParts));
                        $hasSnippet = $rule->getWrongCode() !== '' || $rule->getCorrectCode() !== '';
                    @endphp

                    <div class="rule-item card mb-3 shadow-sm"
                         data-search="{{ $searchHaystack }}">
                        <div class="card-body p-4">
                            <a name="{{ $rule->getSlug() }}"></a>

                            <div class="d-flex justify-content-between align-items-start mb-2 flex-wrap">
                                <h3 class="mt-0 mb-1" style="font-size: 1.2em;">
                                    {{ $rule->getName() }}
                                </h3>
                                @if ($rule->getNodeType())
                                    <span class="badge text-bg-light text-secondary" style="font-weight: normal;">
                                        Node: <code>{{ $rule->getNodeType() }}</code>
                                    </span>
                                @endif
                            </div>

                            <p class="mb-2" style="font-family: monospace; font-size: .85em; color: #666; word-break: break-all;">
                                {{ $rule->getClass() }}
                            </p>

                            @if ($rule->getDescription())
                                <p class="mb-2">{{ $rule->getDescription() }}</p>
                            @endif

                            @if ($rule->getMessage())
                                <p class="mb-3" style="font-size: .95em;">
                                    <em class="text-secondary">Reports:</em>
                                    <code style="background: #f8f9fa; padding: .15em .4em; border-radius: 3px;">{{ $rule->getMessage() }}</code>
                                </p>
                            @endif

                            @if ($hasSnippet)
                                <div class="row mt-3">
                                    @if ($rule->getWrongCode())
                                        <div class="col-12 {{ $rule->getCorrectCode() ? 'col-md-6' : '' }}">
                                            <div class="text-danger mb-1" style="font-size: .9em;">
                                                <strong>&#x2717; Wrong</strong>
                                            </div>
                                            <pre style="background: #fff5f5; border: 1px solid #f5c2c7; border-radius: .3em; padding: .8em; font-size: .85em; overflow-x: auto; max-height: 18em;"><code>{{ $rule->getWrongCode() }}</code></pre>
                                        </div>
                                    @endif
                                    @if ($rule->getCorrectCode())
                                        <div class="col-12 {{ $rule->getWrongCode() ? 'col-md-6' : '' }}">
                                            <div class="text-success mb-1" style="font-size: .9em;">
                                                <strong>&#x2713; Correct</strong>
                                            </div>
                                            <pre style="background: #f0fdf4; border: 1px solid #badbcc; border-radius: .3em; padding: .8em; font-size: .85em; overflow-x: auto; max-height: 18em;"><code>{{ $rule->getCorrectCode() }}</code></pre>
                                        </div>
                                    @endif
                                </div>
                            @endif
                        </div>
                    </div>
                @endforeach
            </div>
        @endforeach

        <script>
            (function () {
                const searchInput = document.getElementById('rule-search');
                const ruleItems = document.querySelectorAll('.rule-item');
                const ruleGroups = document.querySelectorAll('.rule-group');
                const noResults = document.getElementById('no-results');
                const matchCount = document.getElementById('search-match-count');

                // pre-compute per-item search data once
                const items = Array.from(ruleItems).map(function (el) {
                    const haystack = el.getAttribute('data-search') || '';
                    return {
                        el: el,
                        haystack: haystack,
                        compact: haystack.replace(/\s+/g, ''),       // "arra y" -> "array" matches
                        tokens: haystack.match(/[a-z0-9]+/g) || [],  // for per-word fuzzy
                    };
                });

                function levenshtein(a, b) {
                    const m = a.length, n = b.length;
                    if (m === 0) return n;
                    if (n === 0) return m;
                    let prev = new Array(n + 1);
                    let curr = new Array(n + 1);
                    for (let j = 0; j <= n; j++) prev[j] = j;
                    for (let i = 1; i <= m; i++) {
                        curr[0] = i;
                        const ca = a.charCodeAt(i - 1);
                        for (let j = 1; j <= n; j++) {
                            const cost = ca === b.charCodeAt(j - 1) ? 0 : 1;
                            curr[j] = Math.min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + cost);
                        }
                        const tmp = prev; prev = curr; curr = tmp;
                    }
                    return prev[n];
                }

                // typo tolerance scales with word length
                function fuzzyThreshold(len) {
                    if (len <= 3) return 0;
                    if (len <= 5) return 1;
                    return 2;
                }

                function tokenMatches(qt, tokens) {
                    // substring against any haystack token (handles "forbid cast" inside "forbidcast")
                    for (let i = 0; i < tokens.length; i++) {
                        if (tokens[i].indexOf(qt) !== -1) return true;
                    }
                    const threshold = fuzzyThreshold(qt.length);
                    if (threshold === 0) return false;
                    for (let i = 0; i < tokens.length; i++) {
                        const t = tokens[i];
                        if (Math.abs(t.length - qt.length) > threshold) continue;
                        if (levenshtein(qt, t) <= threshold) return true;
                    }
                    return false;
                }

                function matches(item, query, compactQuery, queryTokens) {
                    if (query === '') return true;
                    if (item.haystack.indexOf(query) !== -1) return true;
                    if (compactQuery.length > 1 && item.compact.indexOf(compactQuery) !== -1) return true;
                    if (queryTokens.length === 0) return false;
                    for (let i = 0; i < queryTokens.length; i++) {
                        if (!tokenMatches(queryTokens[i], item.tokens)) return false;
                    }
                    return true;
                }

                function applyFilter() {
                    const query = searchInput.value.trim().toLowerCase();
                    const compactQuery = query.replace(/\s+/g, '');
                    const queryTokens = query.match(/[a-z0-9]+/g) || [];
                    let totalVisible = 0;

                    for (let i = 0; i < items.length; i++) {
                        const item = items[i];
                        const visible = matches(item, query, compactQuery, queryTokens);
                        item.el.style.display = visible ? '' : 'none';
                        if (visible) totalVisible++;
                    }

                    ruleGroups.forEach(function (group) {
                        const visible = group.querySelectorAll('.rule-item:not([style*="display: none"])');
                        group.style.display = visible.length === 0 ? 'none' : '';
                    });

                    noResults.style.display = totalVisible === 0 ? '' : 'none';

                    if (query === '') {
                        matchCount.style.display = 'none';
                    } else {
                        matchCount.textContent = totalVisible + ' of ' + items.length + ' rules match';
                        matchCount.style.display = '';
                    }
                }

                function syncUrl() {
                    const query = searchInput.value.trim();
                    const url = new URL(window.location.href);
                    if (query === '') {
                        url.searchParams.delete('q');
                    } else {
                        url.searchParams.set('q', query);
                    }
                    window.history.replaceState(null, '', url.toString());
                }

                searchInput.addEventListener('input', function () {
                    applyFilter();
                    syncUrl();
                });

                // honour ?q= in URL
                const params = new URLSearchParams(window.location.search);
                if (params.has('q')) {
                    searchInput.value = params.get('q');
                    applyFilter();
                }
            })();
        </script>
@endsection
