#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';
$status = $app->handleCommand(new \Symfony\Component\Console\Input\ArgvInput());

exit($status);
