parameters:
    # used by https://www.tomasvotruba.cz/package-downloads-by-version/
    versioned_framework_vendor:
        # the order reflects similar order in previous table, so it's easier to read
        symfony: Symfony
        cakephp: CakePHP
        illuminate: Laravel
        yiisoft: Yii
        zendframework: Zend
        nette: Nette
        doctrine: Doctrine

    excluded_framework_packages:
        # out there, but too fresh (remove in 2020)
        - 'symfony/security-guard'
        - 'symfony/security-http'
        - 'symfony/security-csrf'
        # framework irrelevant
        - 'symfony/lts'
        - 'symfony/thanks'
        # rather "utils" packages
        - 'symfony/polyfill'
        - 'symfony/polyfill-intl-grapheme'
        - 'symfony/polyfill-intl-normalizer'
        - 'symfony/polyfill-intl-idn'
        - 'symfony/polyfill-xml'
        - 'symfony/polyfill-php54'
        - 'symfony/polyfill-php55'
        - 'symfony/polyfill-php56'
        - 'symfony/polyfill-php70'
        - 'symfony/polyfill-php71'
        - 'symfony/polyfill-php72'
        - 'symfony/polyfill-php73'
        - 'symfony/polyfill-php74'
        - 'symfony/polyfill-apcu'
        - 'symfony/polyfill-util'
        - 'symfony/polyfill-iconv'
        - 'symfony/polyfill-ctype'
        - 'symfony/polyfill-mbstring'
        - 'symfony/polyfill-intl-icu'
        # pseudo-packages
        - 'symfony/apache-pack'
        - 'symfony/serializer-pack'
        - 'symfony/debug-pack'
        - 'symfony/profiler-pack'
        - 'symfony/orm-pack'
        - 'symfony/webpack-encore-pack'
        # deprecated
        - 'symfony/class-loader'
        - 'symfony/assetic-bundle'
        - 'symfony/locale'
        - 'symfony/icu'
        - 'symfony/swiftmailer-bridge'
        - 'illuminate/html'
        # specific integrations
        - 'doctrine/doctrine-module'
        - 'doctrine/doctrine-orm-module'
        - 'doctrine/doctrine-fixtures-bundle'
        - 'doctrine/doctrine-bundle'
        - 'doctrine/doctrine-migrations-bundle'
        - 'doctrine/doctrine-cache-bundle'
        - 'doctrine/mongodb-odm-bundle'
        # weak packages
        - 'cakephp/elastic-search'
        - 'cakephp/acl'
        - 'yiisoft/yii2-apidoc'
        - 'zendframework/zend-expressive-zendrouter'
        - 'zendframework/zend-expressive-twigrenderer'
        - 'zendframework/zend-expressive-zendviewrenderer'
        - 'zendframework/zend-expressive-tooling'
        # meta packages
        - 'symfony/contracts'
        - 'illuminate/contracts'
        - 'symfony/translation-contracts'
        - 'symfony/http-client-contracts'
        - 'symfony/event-dispatcher-contracts'
        - 'symfony/service-contracts'
        # meta-framework packages
        - 'symfony/mercure'
        - 'symfony/panther'

    # used by https://www.tomasvotruba.cz/php-framework-trends/
    frameworks_vendor_to_name:
        nette: Nette
        symfony: Symfony
        # includes also laravel/framework
        illuminate: Laravel
        cakephp: CakePHP
        # single monorepos
        zendframework: Zend
        yiisoft: Yii
        # db "frameworks"
        doctrine: Doctrine
