name: Code_Checks

on:
    - pull_request

jobs:
    ecs:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run:
                    composer install --no-progress

            -
                name: Run
                run:
                    composer fix-cs

            # cannot commit into PRs, master only https://github.com/stefanzweifel/git-auto-commit-action/issues/25
#            -
#                name: Commit changed files
#                uses: stefanzweifel/git-auto-commit-action@v2.5.0
#                with:
#                    commit_message: Apply ECS changes
#                    branch: ${{ github.head_ref }}
#                env:
#                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run:
                    composer install --no-progress

            -
                name: Run
                run:
                    composer phpstan

    rector:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run:
                    composer install --no-progress

            -
                name: Run
                run:
                    composer rector


    unit_tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['7.3', '7.4']

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # default is xdebug
                    extensions: mbstring # needed by phpunit

            -
                name: Install
                run:
                    composer install --no-progress

            -
                name: Run
                run:
                    vendor/bin/phpunit
