name: Monthly Pull Request

on:
    # to try it out
    schedule:
        # every 1st day in month at 12:00 https://crontab.guru/#00_12_1_*_*
        -   cron: "00 12 1 * *"

jobs:
    monthly_pull_request:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: Re-Generate Framework Stats
                        run: bin/console generate-stats --ansi
                        # to prevent mutual override
                        branch: re-generated-framework-stats

        name: ${{ matrix.actions.name }}

        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    tools: composer:v2

            -   run: composer install --no-progress --ansi --ignore-platform-reqs

            -   run: ${{ matrix.actions.run }}
                env:
                     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            # fix coding standards
            -   run: 'composer fix-cs --ansi'

            # see https://github.com/peter-evans/create-pull-request
            -
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    title: "${{ matrix.actions.name }}"
                    commit-message: "${{ matrix.actions.name }}"
                    base: "master"
                    delete-branch: true
                    author: "kaizen-ci <info@kaizen-ci.org>"
                    committer: "kaizen-ci <info@kaizen-ci.org>"
