name: Monthly Pull Request

on:
    push: null

    # to try it out
    schedule:
        # every 1st day in month at 12:00 https://crontab.guru/#00_12_1_*_*
        -   cron: "00 12 1 * *"

    pull_request: null

jobs:
    monthly_pull_request:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: Re-Generate Framework Stats
                        run: bin/console generate-stats --ansi

                    -
                        name: Re-Generate Thank You Contributors
                        run: bin/console thank-contributors --ansi

        name: ${{ matrix.actions.run }}

        steps:
            -
                # see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#example-4
                run: echo "CURRENT_MONTH=$(echo date::$('%Y-%m'))" >> $GITHUB_ENV

            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.run }}

            # see https://github.com/peter-evans/create-pull-request
            -
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    commit-message: "update framework stats ${{ CURRENT_MONTH }}"
                    branch: ci-generated-framework-stats
                    base: 'master'
                    title: "Automated Update of Framework Stats for ${{CURRENT_MONTH }}"
                    delete-branch: true
                    author: "kaizen-ci <info@kaizen-ci.org>"
